version: "3"
services:
  letsjam:
    image: node:16
    container_name: letsjam
    volumes:
      - ./:/home/letsjam
    working_dir: /home/letsjam
    ports:
      - "5173:5173"
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Paris
      - HOST=0.0.0.0
    restart: unless-stopped
    tty: true